# Generated by Django 4.1.3 on 2022-12-05 13:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_category_comments_auctionlistings'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
