# Generated by Django 4.1.3 on 2022-12-09 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctionlistings_watchlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='active_item',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='auctions.category'),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
